#For definition of points look at OneNote

goal_points: [ # Red Points
             [1.77, -0.45, 0.34],
             [1.77, -0.45, 0.84],
             [1.77, 0.45, 0.34],
             [1.77, 0.45, 0.84],
             [1.77, 0.0, 0.34],
             [1.77, 0.0, 0.84],
             [0.94, 0.57, 0.84],
             [0.94, 0.57, 0.34],
             [0.94, -0.57, 0.84 ],
             [0.94, -0.57, 0.34 ],
             # Green Points
             [0.94, 0.74, 1.46],
             [1.77, 0.74, 1.46],
             [0.94, -0.74, 1.46],
             [1.77, -0.74, 1.46],
             [0.94, 0.0, 1.46],
             [1.77, 0.0, 1.46],
             # Blue Points
             [0.94, 0.76, 0.1],
             [0.94, -0.76, 0.1],
             [0.94, -0.76, 1.3],
             [0.94, 0.76, 1.3],
             [1.77, 0.76, 0.1],
             [1.77, -0.76, 0.1],
             [1.77, -0.76, 1.3],
             [1.77, 0.76, 1.3],
             # Yellow Points
             [2.0, 2.0, 0.0],
             [2.0, 2.0, 1.5],
             [2.0, -2.0, 0.0],
             [2.0, -2.0, 1.5],
             [-2.0, 2.0, 0.0],
             [-2.0, 2.0, 1.5],
             [-2.0, -2.0, 0.0],
             [-2.0, -2.0, 1.5]
             ]