tsdf_voxel_size: 0.05
tsdf_voxels_per_side: 16
world_frame: odom

#start_position: [[0.0, 0.0, 0.0], [0.0, -1.57, 0.0, 0.0, -2.0, 0.0]]
#start_position: [[0.0, -2.0, 1.57], [0.0, -1.64, -1.49, 0.0, -1.56, 0.0]] # World 0, 2, 5
start_position: [[-0.6, 0.4, 1.27], [0.0, -1.64, -1.49, 0.0, -1.56, 0.0]] # World 1, 3, 6
#start_position: [[-1.2, -4.0, 1.27], [0.0, -1.64, -1.49, 0.0, -1.56, 0.0]] # World 4

# Johannes collision
#collision_points: [[],[],[],[],[],[[1.0, 0.2], [0.75, 0.2], [0.5, 0.2], [0.25, 0.2], [0.0, 0.2]],[],[]]

# Collision without base
#collision_points: [[],[[0.0,0.3]],[],[[0.75,0.3], [0.5, 0.3], [0.25, 0.3], [0.0, 0.35]],[],[[1.0, 0.22], [0.75, 0.2], [0.5, 0.2], [0.25, 0.2], [0.0, 0.3]],[],[[0.5, 0.1]]]

#Collision one ball for base
collision_points: [[[0.5, 0.55]],[[0.0,0.3]],[],[[0.75,0.3], [0.5, 0.3], [0.25, 0.3], [0.0, 0.35]],[],[[1.0, 0.22], [0.75, 0.2], [0.5, 0.2], [0.25, 0.2], [0.0, 0.3]],[],[[0.5, 0.1]]]

path_world: /home/nick/mpc_ws/src/perceptive_mpc/maps/esdfs/world_6.esdf
#path_world: /home/nick/mpc_ws/src/perceptive_mpc/maps/example_map.esdf