world: world_0
goal_points: [ # corners
  [4.7, 4.7, 0.1],
  [4.7, -4.7, 0.1],
  [-4.7, 4.7, 0.1],
  [-4.7, -4.7, 1.5],
  [ 4.7, 4.7, 1.5 ],
  [ 4.7, -4.7, 1.5 ],
  [ -4.7, 4.7, 1.5 ],
  [ -4.7, -4.7, 1.5 ],
  # mid wall
  [-2.0, -3.0, 0.1],
  [-2.0, 3.0, 0.1],
  [-2.0, 0.0, 0.1],
  [-1.6, -3.0, 0.1],
  [-1.6, 3.0, 0.1],
  [-1.6, 0.0, 0.1],
  [ -2.0, -3.0, 1.5 ],
  [ -2.0, 3.0, 1.5 ],
  [ -2.0, 0.0, 1.5 ],
  [ -1.6, -3.0, 1.5 ],
  [ -1.6, 3.0, 1.5 ],
  [ -1.6, 0.0, 1.5 ],
  # table
  [3.7, -0.8, 0.1], #Points on ground
  [3.7, 0.8, 0.1],
  [ 4.2, -0.8, 0.1 ],
  [ 4.2, 0.8, 0.1 ],
  [ 4.7, -0.8, 0.1 ],
  [ 4.7, 0.8, 0.1 ],
  [ 3.7, 0.0, 0.1],
  [ 4.2, 0.0, 0.1],
  [ 4.7, 0.0, 0.1],
  [ 3.7, -0.8, 0.8 ], # Points underneath table plate
  [ 3.7, 0.8, 0.8 ],
  [ 4.2, -0.8, 0.8 ],
  [ 4.2, 0.8, 0.8 ],
  [ 4.7, -0.8, 0.8 ],
  [ 4.7, 0.8, 0.8 ],
  [ 3.7, 0.0, 0.8 ],
  [ 4.2, 0.0, 0.8 ],
  [ 4.7, 0.0, 0.8 ],
#  [ 3.7, -1.1, 0.1 ], outside table
#  [ 3.7, 1.1, 0.1 ],
#  [ 4.2, -1.1, 0.1 ],
#  [ 4.2, 1.1, 0.1 ],
#  [ 4.7, -1.1, 0.1 ],
#  [ 4.7, 1.1, 0.1 ],
  [ 3.7, -0.8, 1.1 ], # Points on top of table
  [ 3.7, 0.8, 1.1 ],
  [ 4.2, -0.8, 1.1 ],
  [ 4.2, 0.8, 1.1 ],
  [ 4.7, -0.8, 1.1 ],
  [ 4.7, 0.8, 1.1 ],
  [ 3.7, 0.0, 1.1 ],
  [ 4.2, 0.0, 1.1 ],
  [ 4.7, 0.0, 1.1 ]
  ]